### ISSUE TITLE
References in vignette broken

### ISSUE THREAD

**Issue by samclifford** [davidbolin/rSPDE#1]
https://cran.r-project.org/web/packages/rSPDE/vignettes/rspde.html

The references to Lindgren et al. (2011) and Bolin and Kirchner (2019) render as `[@lindgren11]` and `[@bolin19]`.

**Comment by davidbolin** [comment]
Thanks for pointing this out. The references are working if the package is built from source, but as far as I can tell there is a problem with using Bibtex in Vignettes on CRAN. I am changing to inline citations in the vignette which hopefully should solve the issue. I will close the issue after the current development version is submitted to CRAN.

**Comment by davidbolin** [comment]
The correction is now live on CRAN.
