### ISSUE TITLE
Void weight error

### ISSUE THREAD

**Issue by wangk0b** [davidbolin/rSPDE#4]
library(INLA)
library(rSPDE)

lon_k=c(34.59662, 34.83981, 34.81345, 34.85330, 34.88806, 35.08307, 35.06238, 35.09753,35.07159,35.05078)
lat_k=c(28.10111, 28.11987, 28.38795, 28.60698, 28.87952, 28.13824, 28.35275, 28.62534,28.89326,29.10754)
print(lon_k)
print(lat_k)
Y=c(-0.8460002, -0.9349247, -0.7156316, -0.6972056, -0.7092662, -0.1926524,  0.1116601,-0.4543502, -0.4328995, -0.8421882 )
print(Y)
prmesh=inla.mesh.2d(loc.domain = cbind(lon_k,lat_k),max.edge = c(0.5,5), cutoff = 0.05)
coords=cbind(lon_k,lat_k)
Abar <- rspde.make.A(mesh = prmesh, loc = coords)
rspde_model <- rspde.matern(mesh = prmesh)
mesh.index <- rspde.make.index(name = "field", mesh = prmesh)
stk.dat <- inla.stack(
  data = list(y = Y), A = list(Abar, 1), tag = "est",
  effects = list(c(mesh.index,
                   list(Intercept = 1)),
                 list(long = inla.group(coords[, 1]),
                      lat = inla.group(coords[,2]))))

f.s <- y ~ -1 + Intercept + f(field, model = rspde_model)
rspde_fit <- inla(f.s, family = "Gamma", data = inla.stack.data(stk.dat),
            verbose = FALSE,
            control.inla=list(int.strategy='eb'),
            control.predictor = list(A = inla.stack.A(stk.dat), compute = TRUE))

*** ERROR *** 	INLA.Data1: Gamma data[0] (y) = -0.846 or weight 1 is void

Error in inla.inlaprogram.has.crashed() : 
  The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output carefully.
  If this does not help, please contact the developers at <help@r-inla.org>.
Error in inla.core.safe(formula = formula, family = family, contrasts = contrasts,  : 
  *** Fail to get good enough initial values. Maybe it is due to something else.
Calls: inla -> inla.core.safe

**Comment by davidbolin** [comment]
You cannot have negative values in y when assuming a Gamma likelihood in INLA. You will get the same error even if you exclude the rSPDE model in the linear predictor, or use a standard inla.spde2.matern model. If you just set Y <- exp(Y) before creating the stack, it works fine.
