### ISSUE TITLE
simulate and predict methods for class CBrSPDEobj need revision ahead of Matrix 1.5-5

### ISSUE THREAD

**Issue by jaganmn** [davidbolin/rSPDE#5]
Matrix 1.5-5 will no longer attach a `pivot` attribute to the result of `chol(<dsCMatrix>)`.  The existence of the attribute has not been documented and, indeed, attaching attributes to S4 objects in this way has always been "wrong".

Going forward, your methods should change to using `Cholesky` rather than `chol` if the permutation vector must be known in addition to the triangular Cholesky factor.  Note that `Cholesky(<dsCMatrix>)` returns an object inheriting from `CHMfactor`, which has a `solve` method with a very useful `system` argument.

You can obtain Matrix 1.5-5 from an SVN checkout like so:

```bash
$ svn checkout svn://svn.r-forge.r-project.org/svnroot/matrix/pkg/Matrix
$ R CMD build Matrix
$ R CMD INSTALL Matrix_1.5-5.tar.gz
```

Once installed, see these help pages for details:

```r
help("CHMfactor-class", package = "Matrix")
help("Cholesky", package = "Matrix")
help("solve-methods", package = "Matrix")
```

We have not yet discussed a timeline for releasing Matrix 1.5-5, so for now this is just an FYI ... Do let me know if you need clarification while adjusting your code.

Thanks very much,
Mikael    { Matrix co-author }

**Comment by AlexandreBSimas** [comment]
Dear Mikael,

Thank you very much for your message here. We have addressed your comments, and we have replaced chol by Cholesky in the appropriate places. Thus, we are not using the pivot attribute anymore.

Best,
Alexandre

**Comment by jaganmn** [comment]
There are two more issues related to the forthcoming Matrix release.  One is addressed in my most recent e-mail to David Bolin, related to `solve` methods.  The other is a new warning signaled with `determinant(Cholesky(A, ...))`, which I think you have in `R/fractional.computations.R` and `R/fractional.operators.R`.  Going forward, package code should pass `sqrt = TRUE` to `determinant` to indicate that `det(L)` (rather than `det(A)`) should be returned.  The default is `sqrt = TRUE`, but our plan is to change to `FALSE` in the future, hence the warning when `sqrt` is missing.

Note that `sqrt = FALSE` is not respected in older versions of Matrix, so for backwards compatibility you really should pass `sqrt = TRUE` and multiply the log modulus by 2 if you need the equivalent of `sqrt = FALSE`.

**Comment by AlexandreBSimas** [comment]
Dear Mikael,

Thank you very much for reaching us with these points. I believe we addressed all issues. 

Now, the check with the new version of the Matrix package is not giving warnings or errors.

Is the issue with the solve (that you mentioned), the one that was giving errors in the unit tests? If so, it is corrected now.

Thank you very much.
Best,
Alexandre

**Comment by jaganmn** [comment]
> Is the issue with the solve (that you mentioned), the one that was giving errors in the unit tests?

Yes, 5 failing tests in `tests/testthat/test.operator.operations.R`.  Thank you very much Alexandre, for being so prompt.  Feel free to close if you feel that you've addressed the problems.

**Comment by AlexandreBSimas** [comment]
Hi Mikael,

Thank you very much for reaching us with these issues. It is much better to address these in advance. The checks are passing now.

Please, always feel free to reach us if any issue occur.

I will close the issue, then.

Best,
Alexandre

**Comment by jaganmn** [comment]
We plan to release Matrix 1.6-0 {bumped from 1.5-5} around July 1, so you can consider updating your package before or around then.
