### ISSUE TITLE
rgdal archived

### ISSUE THREAD

**Issue by rsbivand** [davidbolin/rSPDE#7]
@davidbolin @finnlindgren  rgdal was archived two days ago, so please do move to submit an updated version of rSPDE as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details. I guess the same omitted deletion of a Suggests.

**Comment by finnlindgren** [comment]
The only reference to rgdal I find outside the DESCRIPTION file is the news entry saying it was added as a suggested package. I suspect that was for the same reason it appeared in the excursions package; to allow an older INLA version to be used in the online pkgdown documents. So it should a trivial removal now.

**Comment by AlexandreBSimas** [comment]
Yes, it was there, but it was not being used for anything, indeed. I have removed it now from the suggests.
