### ISSUE TITLE
error in creating rspde.matern(mesh = prmesh)

### ISSUE THREAD

**Issue by junshujiang** [davidbolin/rSPDE#8]
Abar <- rspde.make.A(mesh = prmesh, loc = coords)
rspde_model <- rspde.matern(mesh = prmesh) 

raise the error:

Error: 'inla.external.lib' is not an exported object from 'namespace:INLA'
Traceback:

1. rspde.matern(mesh = prmesh)

**Comment by AlexandreBSimas** [comment]
Hi Junshu, you need to update inla.
